services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8200:80"
    networks:
      - app-network
    depends_on:
      - postgres
    restart: unless-stopped

#Both PostgreSQL and pgAdmin services are connected to this network
#Good excersie to explore bridge (default), host, overlay, macvlan, none
networks:
  app-network:
    driver: bridge 
