// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Bio       sql.NullString `json:"bio"`
	CreatedAt time.Time      `json:"created_at"`
}

type Book struct {
	ID            int32          `json:"id"`
	AuthorID      int32          `json:"author_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	PublishedYear sql.NullInt32  `json:"published_year"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
