// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	// queries/001_author.sql
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	// queries/002_book.sql
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	DeleteAuthor(ctx context.Context, id int32) error
	DeleteBook(ctx context.Context, id int32) error
	GetAuthor(ctx context.Context, id int32) (Author, error)
	GetBook(ctx context.Context, id int32) (Book, error)
	ListAuthors(ctx context.Context) ([]Author, error)
	ListBooksByAuthor(ctx context.Context, id int32) ([]Book, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
}

var _ Querier = (*Queries)(nil)
